image: rmflight-rpeakcharacterization

runit:
  script:
    - R CMD INSTALL .
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R -e "devtools::test()"
    - Rscript -e "write('There was an error!', stderr()); q('no', 1, FALSE)"
