image: rmflight-rpeakcharacterization

runit:
  script:
  #  - export run_peakpicking=FALSE
    - R CMD INSTALL .
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - Rscript run_tests.R
