image: rmflight-rpeakcharacterization

runit:
  script:
    - R CMD INSTALL .
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - pwd; ls
    - Rscript -e run_tests.R
